#!/usr/bin/env tsx
// == ARGUS AGENT PROJECT ==
/**
 * Regenerate the price catalog shipped with Argus from the AI API Pricing dataset.
 *
 *   tsx scripts/build-pricing-catalog.ts <dataset.csv> [retrieved-YYYY-MM-DD]
 *
 * The dataset (https://aicostbudget.com/en/datasets/ai-api-pricing, CC BY 4.0)
 * is normalized by the meter's own `normalizeDataset`, so the snapshot and a
 * later live refresh agree, and written to `packages/ops-meter/src/catalog-snapshot.ts`.
 * The source CSV is kept next to it for reproducibility.
 */
import { copyFileSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { DATASET_META, normalizeDataset, type Catalog } from '../packages/ops-meter/src/catalog.js'

/**
 * Parse RFC 4180 CSV: quoted fields, doubled quotes, newlines inside quotes.
 * @param text the CSV text.
 * @returns one object per data row, keyed by the header.
 */
export function parseCsv(text: string): Record<string, string>[] {
  const records: string[][] = []
  let field = ''
  let record: string[] = []
  let quoted = false
  for (let i = 0; i < text.length; i += 1) {
    const ch = text[i]!
    if (quoted) {
      if (ch === '"' && text[i + 1] === '"') { field += '"'; i += 1 }
      else if (ch === '"') quoted = false
      else field += ch
    } else if (ch === '"') quoted = true
    else if (ch === ',') { record.push(field); field = '' }
    else if (ch === '\n' || ch === '\r') {
      if (ch === '\r' && text[i + 1] === '\n') i += 1
      record.push(field); field = ''
      if (record.some((value) => value !== '')) records.push(record)
      record = []
    } else field += ch
  }
  record.push(field)
  if (record.some((value) => value !== '')) records.push(record)
  const [header, ...rows] = records
  if (header === undefined) return []
  return rows.map((row) => Object.fromEntries(header.map((name, index) => [name, row[index] ?? ''])))
}

function main(): void {
  const source = process.argv[2]
  if (source === undefined) {
    console.error('usage: tsx scripts/build-pricing-catalog.ts <dataset.csv> [retrieved-YYYY-MM-DD]')
    process.exit(1)
  }
  const retrievedAt = process.argv[3] ?? new Date().toISOString().slice(0, 10)
  const entries = normalizeDataset(parseCsv(readFileSync(source, 'utf8')))
  const catalog: Catalog = { meta: { ...DATASET_META, retrievedAt }, entries }
  const root = resolve(import.meta.dirname, '..')
  const target = join(root, 'packages', 'ops-meter', 'src', 'catalog-snapshot.ts')
  writeFileSync(
    target,
    '// == ARGUS AGENT PROJECT ==\n' +
      '// GENERATED by scripts/build-pricing-catalog.ts — do not edit by hand.\n' +
      `// Source: ${catalog.meta.title}, ${catalog.meta.url} (${catalog.meta.license}), retrieved ${retrievedAt}.\n` +
      `// Changes: ${catalog.meta.changes}\n` +
      "import type { Catalog } from './catalog.js'\n\n" +
      '/** The price catalog shipped with this release. */\n' +
      `export const SNAPSHOT: Catalog = ${JSON.stringify(catalog, null, 2)}\n`,
  )
  copyFileSync(source, join(root, 'packages', 'ops-meter', 'catalog', 'ai-api-pricing.csv'))
  console.log(`catalog: ${entries.length} model(s) from ${source} → ${target}`)
}

if (import.meta.filename === process.argv[1]) main()
