// == ARGUS AGENT PROJECT ==
/**
 * The channel contract.
 *
 * `ops-channel` owns the routing, allowlist and delivery policy; an adapter
 * (`ops-telegram`, the test `console` adapter, a future `slack`) only translates
 * between one platform and these types. Defining the contract here — before
 * `ops-channel` exists — lets `ops-testkit` implement an adapter against it in
 * the same change that defines it.
 *
 * @module @argus-agent/types/channel-adapter
 */
import type { ChannelAddress } from './channel.js'

/**
 * A model-facing content block.
 *
 * Structurally the subset of dsh-llm's `ContentBlock` that a channel or a
 * scheduler produces: text, and nothing the model must interpret. Typed here so
 * a plugin can carry verbatim user content without importing dsh-llm's whole
 * block union — and so that "forwarded verbatim" is visible in the type.
 */
export type ContentBlockLike =
  | { readonly type: 'text'; readonly text: string }
  | { readonly type: 'image'; readonly [key: string]: unknown }

/** A file produced by an agent and delivered to a chat. */
export interface OutgoingFile {
  /** File name shown to the recipient. */
  readonly name: string
  /** Absolute path on disk, or inline bytes. */
  readonly path?: string
  readonly bytes?: Uint8Array
  /** MIME type, when known. */
  readonly mimeType?: string
}

/** One button in a question. */
export interface Button {
  /**
   * Opaque value returned when the button is pressed.
   *
   * The adapter must round-trip it unchanged; `ops-channel` correlates answers
   * by this value.
   */
  readonly value: string
  /** Label shown to the user. */
  readonly label: string
}

/** A message leaving the system. */
export interface OutgoingMessage {
  /** Message text. The adapter splits or converts it per its own limits. */
  readonly text: string
  /** Files to attach. */
  readonly files?: readonly OutgoingFile[]
  /** Buttons to render with the message, when the adapter supports them. */
  readonly buttons?: readonly Button[]
  /**
   * Replace the message this reference names instead of sending a new one.
   *
   * Used for progress messages, which edit one message rather than spamming a
   * new one every interval.
   */
  readonly editOf?: MessageRef
}

/** A handle to a message the adapter already sent. */
export interface MessageRef {
  readonly channel: string
  readonly chatId: string
  /** Platform message id. */
  readonly messageId: string
}

/** A file or image a user sent. */
export interface IncomingAttachment {
  readonly kind: 'file' | 'image'
  /** Original file name, when the platform provides one. */
  readonly name: string
  readonly mimeType?: string
  /** Bytes, when the adapter downloaded them within its size limit. */
  readonly bytes?: Uint8Array
  /** Platform file id, when the adapter did not download the file. */
  readonly fileId?: string
  readonly sizeBytes?: number
}

/** A message arriving from a platform. */
export interface IncomingMessage {
  /** Stable platform message id, for deduplication. */
  readonly id: string
  readonly address: ChannelAddress
  /** Platform user identity. Checked against the allowlist by `ops-channel`. */
  readonly userId: string
  /** Display name, for logs. Never trusted for authorization. */
  readonly userName?: string
  /** Message text. Empty when the message carried only attachments. */
  readonly text: string
  readonly attachments?: readonly IncomingAttachment[]
  /** Whether this came from a group chat. */
  readonly isGroup?: boolean
  /** Platform timestamp, epoch ms. */
  readonly timestamp: number
}

/** A button answer from a user. */
export interface ButtonAnswer {
  /** The question this answers. */
  readonly questionId: string
  /** The pressed button's `value`. */
  readonly value: string
  readonly address: ChannelAddress
  readonly userId: string
  readonly timestamp: number
}

/** A question put to a user, with buttons. */
export interface Question {
  /**
   * Correlates the question with its answer.
   *
   * Generated by `ops-channel`; the adapter must return it unchanged in the
   * corresponding {@link ButtonAnswer}.
   */
  readonly id: string
  readonly text: string
  readonly buttons: readonly Button[]
  /** When set, the question resolves `'timeout'` after this many ms. */
  readonly timeoutMs?: number
}

/**
 * What a user answered.
 *
 * `'timeout'` is the single representation of "nobody answered", matching the
 * `ChannelAdapter.ask` return type. There is deliberately no `{kind:'timeout'}`
 * variant: two spellings of the same outcome would let a caller handle one and
 * silently ignore the other.
 */
export type Answer = { readonly kind: 'button'; readonly value: string }

/** A question's outcome: a button press, or nobody answered. */
export type AnswerOrTimeout = Answer | 'timeout'

/** The limits an adapter declares, so callers can respect them. */
export interface AdapterLimits {
  /** Maximum characters in one text message. */
  readonly maxTextLength: number
  /** Maximum attachment size the adapter will send, in bytes. */
  readonly maxFileBytes: number
}

/**
 * One platform adapter.
 *
 * Implementations must be free of business logic: no routing decisions, no
 * allowlist checks, no command parsing. Those live in `ops-channel`.
 */
export interface ChannelAdapter {
  /** Adapter name, matching {@link ChannelAddress.channel}. */
  readonly name: string
  /** The adapter's platform limits. */
  readonly limits: AdapterLimits

  /**
   * Begin receiving messages.
   * @param onMessage called for each incoming message.
   * @param onButton called for each button answer.
   * @returns a disposer that stops receiving and releases resources.
   */
  start(
    onMessage: (message: IncomingMessage) => void,
    onButton: (answer: ButtonAnswer) => void,
  ): Promise<() => Promise<void>>

  /**
   * Send a message.
   * @param to the destination.
   * @param message the message.
   * @returns a handle to the sent message.
   */
  send(to: ChannelAddress, message: OutgoingMessage): Promise<MessageRef>

  /**
   * Edit a message the adapter already sent.
   * @param ref the message to edit.
   * @param message the replacement content.
   */
  edit(ref: MessageRef, message: OutgoingMessage): Promise<void>

  /**
   * Ask a question with buttons.
   *
   * The adapter presents the buttons and resolves when one is pressed or the
   * timeout elapses. It must **not** enforce the allowlist; `ops-channel`
   * discards answers from unauthorized users before they reach this promise.
   *
   * @param to the destination.
   * @param question the question and its buttons.
   * @returns the answer, or `'timeout'`.
   */
  ask(to: ChannelAddress, question: Question): Promise<AnswerOrTimeout>
}
